### ISSUE TITLE
FYI Download directory path changed around Feb 25, 2016

### ISSUE THREAD

**Issue by cablecart** [Asoul/taifex-crawler#1]
examples of the new paths are

https://www.taifex.com.tw/DailyDownload/DailyDownloadCSV/Daily_2016_02_02.zip

https://www.taifex.com.tw/DailyDownload/DailyDownload/Daily_2016_02_02.zip

You might want to consider deleting invalid files (by for example grepping for "javascript") that's how I caught the change.

Cheers

**Comment by Asoul** [comment]
Thanks, it's a long time since last update

**Comment by Asoul** [comment]
I have updated the crawler script, thanks! I thought no one noticed this project, ha!
